<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page import="java.util.*,com.sweetpay.util.*,com.sweetpay.model.Order,com.sweetpay.model.Payment"%>
<% Order customerOrder=(Order)request.getAttribute("order"); Payment customerPayment=(Payment)request.getAttribute("payment");
Map<String,Object> extra=(Map<String,Object>)request.getAttribute("operations");Object message=session.getAttribute("opsMessage");
if(message!=null) { %><div role="status" class="alert <%=Boolean.TRUE.equals(session.getAttribute("opsError"))?"alert-warning":"alert-success"%>"><%=OpsView.e(message)%></div><% session.removeAttribute("opsMessage");session.removeAttribute("opsError"); }
if(customerOrder!=null && extra!=null) { int customerOrderId=customerOrder.getOrderId(); %>
<% if(extra.get("driver_name")!=null) { %><p class="text-muted">Nhân viên giao bánh: <strong><%=OpsView.text(extra,"driver_name")%></strong></p><% } %>
<% if(customerPayment!=null && !Arrays.asList("paid","refunded").contains(customerPayment.getPaymentStatus()) && !Arrays.asList("cancelled","completed").contains(customerOrder.getOrderStatus()) && !"requested".equals(extra.get("cancel_status"))) { %>
<div class="card mb-4"><div class="card-body"><h5>Hoàn tất thanh toán</h5>
<% if("VNPAY".equals(customerPayment.getPaymentMethod())) { %><p>Thanh toán thử nghiệm qua VNPAY. Nếu giao dịch chưa thành công, bạn có thể thử lại.</p>
<form action="<%=request.getContextPath()%>/payments/start" method="post"><input type="hidden" name="csrfToken" value="<%=CsrfUtil.getToken(session)%>"><input type="hidden" name="orderId" value="<%=customerOrderId%>"><button class="btn btn-primary" <%=VnpayConfig.configured()?"":"disabled"%>>Thanh toán qua VNPAY Sandbox</button></form>
<% if(!VnpayConfig.configured()) { %><p class="text-muted mt-2 mb-0">Phương thức này đang tạm ngưng. Vui lòng liên hệ cửa hàng.</p><% } %>
<% } else if("BANK_TRANSFER".equals(customerPayment.getPaymentMethod())) { %><p>Cửa hàng sẽ xác nhận sau khi đối chiếu giao dịch chuyển khoản.</p><a class="btn btn-primary" href="<%=request.getContextPath()%>/payment?orderId=<%=customerOrderId%>">Xem thông tin chuyển khoản</a>
<% } else { %><p class="mb-0">Thanh toán <strong><%=OpsView.money(customerOrder.getTotalAmount())%></strong> khi nhận bánh.</p><% } %></div></div><% } %>
<% if(extra.get("cancel_status")!=null) { %><div class="alert alert-info"><strong><%=OpsView.label(extra.get("cancel_status"))%></strong><br>Lý do: <%=OpsView.text(extra,"cancel_reason")%><% if(extra.get("cancel_review_note")!=null) { %><br>Phản hồi cửa hàng: <%=OpsView.text(extra,"cancel_review_note")%><% } %></div>
<% } else if("pending".equals(customerOrder.getOrderStatus()) && Objects.equals(AuthSessionUtil.getUserId(session),customerOrder.getUserId())) { %>
<details class="card mb-4"><summary class="card-header">Yêu cầu hủy đơn hàng</summary><div class="card-body"><p>Bạn có thể gửi yêu cầu khi cửa hàng chưa xác nhận đơn. Cửa hàng sẽ xem xét và phản hồi tại đây.</p><form action="<%=request.getContextPath()%>/cancel-order" method="post"><input type="hidden" name="csrfToken" value="<%=CsrfUtil.getToken(session)%>"><input type="hidden" name="orderId" value="<%=customerOrderId%>"><label for="cancelReason" class="form-label">Lý do hủy</label><textarea class="form-control mb-3" name="note" id="cancelReason" required maxlength="500" rows="2"></textarea><button class="btn btn-outline-danger">Gửi yêu cầu hủy</button></form></div></details><% } %>
<% if("cancelled".equals(customerOrder.getOrderStatus()) && "paid".equals(customerOrder.getPaymentStatus())) { %><div class="alert alert-warning">Đơn đã hủy và đang chờ cửa hàng xử lý hoàn tiền. Tình trạng thanh toán sẽ được cập nhật sau khi hoàn tiền.</div><% } %>
<% List<Map<String,Object>> entries=(List<Map<String,Object>>)request.getAttribute("history"); if(entries!=null&&!entries.isEmpty()) { %><details class="card mb-4"><summary class="card-header">Lịch sử xử lý đơn hàng</summary><div class="card-body"><ul class="list-unstyled mb-0"><% for(Map<String,Object> entry:entries) { if(!Arrays.asList("transition","cancel_request","reject_cancel","gateway","bank_notice").contains(entry.get("action")))continue; %><li class="mb-2"><small class="text-muted"><%=OpsView.date(entry.get("created_at"))%></small> · <%=OpsView.label(entry.get("action"))%><% if(!Objects.equals(entry.get("from_status"),entry.get("to_status"))) { %>: <strong><%=OpsView.label(entry.get("to_status"))%></strong><% } %></li><% } %></ul></div></details><% } %>
<% } %>
