<%@page pageEncoding="UTF-8"%>
<%@ include file="_header.jspf" %>
<% List<Map<String,Object>> rows=(List<Map<String,Object>>)request.getAttribute("rows");
Map<String,Object> detail=(Map<String,Object>)request.getAttribute("detail");
String base=(String)request.getAttribute("basePath"),path=opsContext+base; boolean admin="admin".equals(opsRole),reconcile=base.endsWith("reconciliation");
String selectedStatus=(String)request.getAttribute("selectedStatus");
%>
<% if(admin && !VnpayConfig.configured()) { %><div class="ops-alert">VNPAY Sandbox chưa được kết nối. COD và chuyển khoản thủ công vẫn dùng được. Xem hướng dẫn cấu hình trong tài liệu dự án để bật thanh toán thử nghiệm.</div><% } %>
<% if(detail==null) { %>
<section class="ops-card"><form class="ops-filter" method="get" action="<%=path%>"><div><label for="q">Tìm đơn hàng</label><input id="q" name="q" value="<%=OpsView.e(request.getAttribute("query"))%>" placeholder="Mã đơn, người nhận, số điện thoại" maxlength="100"></div>
<div><label for="status">Trạng thái</label><select name="status" id="status"><option value="">Tất cả trạng thái</option>
<% for(String state:Arrays.asList("pending","confirmed","preparing","ready_for_delivery","ready_for_pickup","shipping","delivery_failed","completed","cancelled","cancel_requested")) { %>
<option value="<%=state%>" <%=state.equals(selectedStatus)?"selected":""%>><%="cancel_requested".equals(state)?"Có yêu cầu hủy":OpsView.label(state)%></option><% } %></select></div><button>Lọc đơn hàng</button><a class="ops-btn secondary" href="<%=path%>">Đặt lại</a></form></section>
<% if(reconcile) { %><p class="ops-muted">Danh sách dưới đây chỉ gồm đơn cần đối soát: chuyển khoản chưa xác nhận, COD chưa bàn giao, hoặc đơn đã hủy cần hoàn tiền. Chọn “Xử lý” để xem và ghi nhận chứng từ.</p><% } %>
<section class="ops-card"><div class="ops-card-header"><h2><%=reconcile?"Các khoản cần xử lý":"Danh sách đơn hàng"%></h2></div><div class="ops-table-wrap"><table><thead><tr><th>Đơn hàng</th><th>Người nhận</th><th>Tổng tiền</th><th>Tiến độ</th><th>Thanh toán</th><th>Giao nhận</th><th></th></tr></thead><tbody>
<% int shown=0; for(Map<String,Object> row:rows) {
boolean bankDue="BANK_TRANSFER".equals(row.get("payment_method"))&&!Arrays.asList("paid","refunded").contains(row.get("payment_status"))&&!"cancelled".equals(row.get("order_status"));
boolean refundDue="cancelled".equals(row.get("order_status"))&&"paid".equals(row.get("payment_status"));
boolean codDue=row.get("cod_collected_at")!=null&&row.get("cod_remitted_at")==null;
if(reconcile && !bankDue && !refundDue && !codDue) continue; shown++;
%><tr><td><strong><%=OpsView.text(row,"order_code")%></strong><small><%=OpsView.date(row.get("order_date"))%></small></td><td><strong><%=OpsView.text(row,"recipient_name")%></strong><small><%=OpsView.text(row,"recipient_phone")%></small></td>
<td><strong><%=OpsView.money(row.get("total_amount"))%></strong></td><td><span class="ops-badge <%=OpsView.text(row,"order_status")%>"><%=OpsView.label(row.get("order_status"))%></span><% if("requested".equals(row.get("cancel_status"))) { %><small>Khách yêu cầu hủy</small><% } %></td>
<td><span class="ops-badge <%=OpsView.text(row,"payment_status")%>"><%="pending".equals(row.get("payment_status"))?"Chờ thanh toán":OpsView.label(row.get("payment_status"))%></span><small><%=OpsView.label(row.get("payment_method"))%></small><% if(codDue) { %><small>COD chờ bàn giao</small><% } if(refundDue) { %><small>Cần hoàn tiền</small><% } %></td>
<td><%=OpsView.label(row.get("receive_method"))%><small><%=row.get("driver_name")==null?"Chưa phân công":OpsView.text(row,"driver_name")%></small></td><td><a class="ops-btn secondary" href="<%=path%>?id=<%=OpsView.id(row,"order_id")%>#order-detail">Xử lý</a></td></tr>
<% } if(shown==0) { %><tr><td colspan="7" class="ops-empty"><%=reconcile?"Không có khoản cần đối soát trong bộ lọc này.":"Chưa có đơn hàng phù hợp."%></td></tr><% } %>
</tbody></table></div></section>
<% } else { %><p><a class="ops-link" href="<%=path%>">← Về danh sách <%=reconcile?"đối soát":"đơn hàng"%></a></p><% } %>
<% if(detail!=null) {
int oid=OpsView.id(detail,"order_id"); String state=Sql.string(detail,"order_status"),method=Sql.string(detail,"receive_method"),payment=Sql.string(detail,"payment_status"),payMethod=Sql.string(detail,"payment_method");
List<String> next=OrderPolicy.next(opsRole,state,method);
if("requested".equals(detail.get("cancel_status"))) next.removeIf(v->!"cancelled".equals(v));
if(!"COD".equals(payMethod)&&!"paid".equals(payment)) next.removeIf(v->Arrays.asList("confirmed","shipping","completed").contains(v));
if(detail.get("driver_id")==null) next.removeIf(v->"shipping".equals(v)||"delivery_failed".equals(v)||"completed".equals(v)&&"delivery".equals(method));
%>
<div id="order-detail" class="ops-detail-anchor ops-two"><section class="ops-card"><div class="ops-card-header"><h2><%=OpsView.text(detail,"order_code")%></h2><span class="ops-badge <%=OpsView.e(state)%>"><%=OpsView.label(state)%></span></div>
<div class="ops-detail-grid"><div><small>Người nhận</small><strong><%=OpsView.text(detail,"recipient_name")%></strong></div><div><small>Liên hệ</small><%=OpsView.text(detail,"recipient_phone")%></div><div><small>Địa chỉ</small><%=OpsView.text(detail,"shipping_address")%></div><div><small>Hình thức nhận</small><%=OpsView.label(method)%></div><div><small>Ghi chú của khách</small><span class="ops-note"><%=OpsView.text(detail,"note")%></span></div><div><small>Người giao hàng</small><%=detail.get("driver_name")==null?"Chưa phân công":OpsView.text(detail,"driver_name")%></div></div>
<div class="ops-table-wrap"><table><thead><tr><th>Bánh</th><th>SL</th><th>Thành tiền</th></tr></thead><tbody><% for(Map<String,Object> line:(List<Map<String,Object>>)request.getAttribute("lines")) { %><tr><td><strong><%=OpsView.text(line,"product_name")%></strong><small><%=OpsView.text(line,"flavor")%> · <%=OpsView.text(line,"size")%></small></td><td><%=OpsView.text(line,"quantity")%></td><td><%=OpsView.money(line.get("line_total"))%></td></tr><% } %></tbody></table></div>
<div class="ops-detail-grid"><div><small>Giảm giá</small><%=OpsView.money(detail.get("discount_amount"))%></div><div><small>Cần thanh toán</small><strong><%=OpsView.money(detail.get("total_amount"))%></strong></div></div>
<% if(detail.get("failure_reason")!=null) { %><div class="ops-alert ops-alert-error">Lần giao trước: <%=OpsView.text(detail,"failure_reason")%></div><% } %>
<% if(detail.get("cancel_status")!=null) { %><div class="ops-alert <%= "requested".equals(detail.get("cancel_status"))?"ops-alert-error":""%>"><strong><%=OpsView.label(detail.get("cancel_status"))%></strong><br>Lý do khách gửi: <%=OpsView.text(detail,"cancel_reason")%><% if(detail.get("cancel_review_note")!=null) { %><br>Phản hồi: <%=OpsView.text(detail,"cancel_review_note")%><% } %></div><% } %>
<% if(admin && "requested".equals(detail.get("cancel_status"))) { %><form action="<%=path%>" method="post" class="ops-section"><%@ include file="_csrf.jspf" %><input type="hidden" name="orderId" value="<%=oid%>"><input type="hidden" name="action" value="reject_cancel"><label for="reject-note">Lý do không duyệt yêu cầu hủy</label><textarea name="note" id="reject-note" required maxlength="500" rows="2"></textarea><button class="secondary" style="margin-top:10px">Không duyệt hủy</button></form><% } %>
<% if(admin && "delivery".equals(method) && Arrays.asList("confirmed","preparing","ready_for_delivery","delivery_failed").contains(state) && !"requested".equals(detail.get("cancel_status"))) { %>
<form action="<%=path%>" method="post" class="ops-section"><%@ include file="_csrf.jspf" %><input type="hidden" name="orderId" value="<%=oid%>"><input type="hidden" name="action" value="assign"><h3>Phân công giao hàng</h3><label for="driverId">Nhân viên giao hàng</label><div class="ops-actions"><select name="driverId" id="driverId" required style="flex:1"><option value="">Chọn nhân viên</option><% for(Map<String,Object> staff:(List<Map<String,Object>>)request.getAttribute("staff")) { if(!"delivery_staff".equals(staff.get("role_name")) || !OpsView.active(staff)) continue; %><option value="<%=OpsView.id(staff,"user_id")%>" <%=OpsView.id(staff,"user_id")==OpsView.id(detail,"driver_id")?"selected":""%>><%=OpsView.text(staff,"full_name")%></option><% } %></select><button>Lưu phân công</button></div></form><% } %>
<% if(!next.isEmpty()) { %><form action="<%=path%>" method="post" class="ops-section"><%@ include file="_csrf.jspf" %><input type="hidden" name="orderId" value="<%=oid%>"><input type="hidden" name="action" value="transition"><h3>Cập nhật tiến độ</h3><div class="ops-form-grid"><div class="wide"><label for="target">Bước tiếp theo</label><select name="target" id="target" required><% for(String step:next) { %><option value="<%=step%>"><%=OpsView.label(step)%></option><% } %></select></div><div class="wide"><label for="progress-note">Ghi chú (bắt buộc khi hủy hoặc giao thất bại)</label><textarea name="note" id="progress-note" maxlength="500" rows="2"></textarea></div>
<% if("COD".equals(payMethod)&&!"paid".equals(payment)&&next.contains("completed")) { %><div class="wide"><label class="ops-check"><input type="checkbox" name="collected" value="yes">Tôi đã thu đủ <strong><%=OpsView.money(detail.get("total_amount"))%></strong> từ khách.</label></div><% } %><div class="wide"><button>Cập nhật đơn hàng</button></div></div></form><% } else { %><p class="ops-muted ops-section">Chưa có bước xử lý tiếp theo cho vai trò này. Kiểm tra thanh toán, yêu cầu hủy hoặc phân công giao hàng.</p><% } %>
</section><div><section class="ops-card"><h2>Thanh toán & đối soát</h2><div class="ops-detail-grid"><div><small>Phương thức</small><%=OpsView.label(payMethod)%></div><div><small>Tình trạng</small><%="pending".equals(payment)?"Chờ thanh toán":OpsView.label(payment)%></div><div><small>Mã giao dịch</small><span class="ops-code"><%=OpsView.text(detail,"transaction_code")%></span></div><div><small>Thời gian thanh toán</small><%=OpsView.date(detail.get("paid_at"))%></div></div>
<% if(detail.get("cod_collected_at")!=null) { %><p class="ops-muted">Đã thu COD: <%=OpsView.date(detail.get("cod_collected_at"))%><br>Bàn giao: <%=OpsView.date(detail.get("cod_remitted_at"))%><br>Biên nhận: <%=OpsView.text(detail,"cod_remit_reference")%></p><% } %>
<% String financialAction=null,financialTitle="",financialHint="";
if(admin && "BANK_TRANSFER".equals(payMethod)&&!Arrays.asList("paid","refunded").contains(payment)) { financialAction="bank_confirm"; financialTitle="Xác nhận đã nhận chuyển khoản"; financialHint="Đối chiếu số tiền và nội dung trên sao kê ngân hàng trước khi xác nhận."; }
if(admin && detail.get("cod_collected_at")!=null&&detail.get("cod_remitted_at")==null) { financialAction="remit";financialTitle="Ghi nhận bàn giao tiền COD";financialHint="Xác nhận cửa hàng đã nhận đủ tiền từ nhân viên giao hàng."; }
if(admin && "cancelled".equals(state)&&"paid".equals(payment)) { financialAction="refund";financialTitle="Ghi nhận đã hoàn tiền";financialHint="Thực hiện hoàn tiền qua ngân hàng hoặc cổng thanh toán trước, sau đó nhập mã chứng từ. Thao tác này chỉ ghi nhận kết quả hoàn tiền."; }
if(financialAction!=null) { %><form action="<%=path%>" method="post" class="ops-section" data-confirm="Bạn đã kiểm tra chứng từ và xác nhận khoản tiền này?"><%@ include file="_csrf.jspf" %><input type="hidden" name="orderId" value="<%=oid%>"><input type="hidden" name="action" value="<%=financialAction%>"><h3><%=financialTitle%></h3><p class="ops-muted"><%=financialHint%></p><label for="reference">Mã giao dịch / biên nhận</label><input name="reference" id="reference" required maxlength="100"><label for="financial-note" style="margin-top:12px">Ghi chú chứng từ</label><textarea name="note" id="financial-note" maxlength="500" rows="2" <%="refund".equals(financialAction)?"required":""%>></textarea><button style="margin-top:12px">Xác nhận <%=OpsView.money(detail.get("total_amount"))%></button></form><% } %>
</section><section class="ops-card" style="margin-top:22px"><h2>Lịch sử xử lý</h2><ol class="ops-timeline"><% List<Map<String,Object>> history=(List<Map<String,Object>>)request.getAttribute("history"); for(Map<String,Object> entry:history) { %><li><strong><%=OpsView.label(entry.get("action"))%></strong><% if(!Objects.equals(entry.get("from_status"),entry.get("to_status"))) { %><div><%=OpsView.label(entry.get("from_status"))%> → <%=OpsView.label(entry.get("to_status"))%></div><% } %><div class="ops-note"><%=OpsView.text(entry,"note")%></div><small><%=OpsView.date(entry.get("created_at"))%> · <%=entry.get("actor_name")==null?"Cổng thanh toán":OpsView.text(entry,"actor_name")%></small></li><% } if(history.isEmpty()) { %><li class="ops-muted">Chưa có cập nhật xử lý.</li><% } %></ol></section></div></div>
<% } %>
<%@ include file="_footer.jspf" %>
