<%@page pageEncoding="UTF-8"%>
<%@ include file="_header.jspf" %>
<% Map<String,List<Map<String,Object>>> report=(Map<String,List<Map<String,Object>>>)request.getAttribute("report");Map<String,Object> summary=report.get("summary").get(0); %>
<section class="ops-card"><form method="get" class="ops-filter"><div><label for="from">Từ ngày đặt hàng</label><input id="from" type="date" name="from" required value="<%=request.getAttribute("from")%>"></div><div><label for="to">Đến hết ngày</label><input id="to" type="date" name="to" required value="<%=request.getAttribute("to")%>"></div><button>Xem báo cáo</button></form></section>
<div class="ops-stats"><div class="ops-stat"><small>Doanh thu đơn hoàn tất, đã thanh toán</small><strong><%=OpsView.money(summary.get("revenue"))%></strong></div><div class="ops-stat"><small>Tổng đơn trong kỳ</small><strong><%=OpsView.id(summary,"order_count")%></strong></div><div class="ops-stat"><small>Đơn hoàn tất</small><strong><%=OpsView.id(summary,"completed_count")%></strong></div><div class="ops-stat"><small>Đơn đã hủy</small><strong><%=OpsView.id(summary,"cancelled_count")%></strong></div></div>
<p class="ops-muted">Doanh thu theo ngày đặt đơn, chỉ tính đơn đã hoàn tất và đã thanh toán, sau giảm giá và gồm phí giao hàng. Tiền COD còn giữ và tồn kho là số liệu hiện tại, không phụ thuộc khoảng ngày.</p>
<div class="ops-two"><section class="ops-card"><h2>Doanh thu theo ngày đặt hàng</h2><div class="ops-table-wrap"><table><thead><tr><th>Ngày</th><th>Số đơn</th><th>Doanh thu</th></tr></thead><tbody><% for(Map<String,Object> row:report.get("daily")) { %><tr><td><%=OpsView.text(row,"day")%></td><td><%=OpsView.text(row,"order_count")%></td><td><%=OpsView.money(row.get("revenue"))%></td></tr><% } if(report.get("daily").isEmpty()) { %><tr><td colspan="3" class="ops-empty">Chưa có đơn trong khoảng ngày này.</td></tr><% } %></tbody></table></div></section>
<section class="ops-card"><h2>Phân bố trạng thái đơn</h2><table><thead><tr><th>Trạng thái</th><th>Số đơn</th></tr></thead><tbody><% for(Map<String,Object> row:report.get("statuses")) { %><tr><td><%=OpsView.label(row.get("order_status"))%></td><td><%=OpsView.text(row,"order_count")%></td></tr><% } %></tbody></table></section></div>
<section class="ops-card" style="margin-top:22px"><h2>10 loại bánh bán chạy</h2><p class="ops-muted">Chỉ tính đơn hoàn tất, đã thanh toán trong kỳ. Giá trị sản phẩm tính trước mã giảm giá và phí giao hàng.</p><table><thead><tr><th>Bánh</th><th>Số lượng</th><th>Giá trị sản phẩm</th></tr></thead><tbody><% for(Map<String,Object> row:report.get("products")) { %><tr><td><%=OpsView.text(row,"product_name")%></td><td><%=OpsView.text(row,"quantity")%></td><td><%=OpsView.money(row.get("gross_sales"))%></td></tr><% } if(report.get("products").isEmpty()) { %><tr><td colspan="3" class="ops-empty">Chưa có sản phẩm bán thành công trong kỳ.</td></tr><% } %></tbody></table></section>
<div class="ops-two"><section class="ops-card"><h2>COD đang chờ bàn giao</h2><table><thead><tr><th>Nhân viên</th><th>Số đơn</th><th>Đang giữ</th></tr></thead><tbody><% for(Map<String,Object> row:report.get("cod")) { %><tr><td><%=OpsView.text(row,"full_name")%></td><td><%=OpsView.text(row,"order_count")%></td><td><%=OpsView.money(row.get("amount"))%></td></tr><% } if(report.get("cod").isEmpty()) { %><tr><td colspan="3" class="ops-empty">Không còn khoản COD chờ bàn giao.</td></tr><% } %></tbody></table><a class="ops-link" href="<%=opsContext%>/admin/reconciliation">Mở đối soát thanh toán →</a></section>
<section class="ops-card"><h2>Bánh cần bổ sung</h2><table><thead><tr><th>Bánh</th><th>Còn lại</th><th>Ngưỡng cảnh báo</th></tr></thead><tbody><% for(Map<String,Object> row:report.get("low_stock")) { %><tr><td><%=OpsView.text(row,"product_name")%></td><td><%=OpsView.text(row,"quantity_in_stock")%></td><td><%=OpsView.text(row,"min_stock_level")%></td></tr><% } if(report.get("low_stock").isEmpty()) { %><tr><td colspan="3" class="ops-empty">Các sản phẩm đang đủ số lượng.</td></tr><% } %></tbody></table></section></div>
<% if(!report.get("duplicates").isEmpty()) { %><section class="ops-card" style="margin-top:22px"><h2>Giao dịch trả tiền trùng cần kiểm tra</h2><p class="ops-muted">Đơn đã nhận tiền trước khi giao dịch này thành công. Cần kiểm tra trên VNPAY để xử lý khoản tiền dư.</p><table><thead><tr><th>Đơn</th><th>Mã VNPAY</th><th>Số tiền dư</th></tr></thead><tbody><% for(Map<String,Object> row:report.get("duplicates")) { %><tr><td><a href="<%=opsContext%>/admin/fulfillment?id=<%=OpsView.id(row,"order_id")%>#order-detail"><%=OpsView.text(row,"order_code")%></a></td><td><%=OpsView.text(row,"transaction_no")%></td><td><%=OpsView.money(row.get("amount"))%></td></tr><% } %></tbody></table></section><% } %>
<%@ include file="_footer.jspf" %>
